### ISSUE TITLE
Assignment 1, 3b

### ISSUE THREAD

**Issue by andreasbinder** [Zhenye-Na/reinforcement-learning-stanford#6]
First of all, thanks for sharing the materials! 

I was wondering whether the solution corresponds to the original one or is collected by the work of multiple students? In particular, I don't quite understand the final step in A1, 3b: 

2ε + γ * Expectation wrt to s [V*(s) − Vpi(s)] = 2ε / (1−γ) 

Could you please explain why that holds? Or link the material clarifying this step please :)

Thanks a lot!

**Comment by Zhenye-Na** [comment]
Hi, thanks for reaching out.

I just collected those codes from internet, I did not finish any of the problem sets yet.

Sorry that I cannot help.
